export const INDUSTRIES = [
  'Apparel & Fashion',
  'Auto Parts & Accessories',
  'Beauty & Cosmetics',
  'Cannabis',
  'Consumer Electronics',
  'CPG / Consumer Packaged Goods',
  'Food & Beverage',
  'Fitness & Wellness',
  'Home & Garden',
  'Industrial & Manufacturing',
  'Jewelry & Watches',
  'Medical & Healthcare',
  'Outdoor & Recreation',
  'Pet Products',
  'Pharmaceuticals',
  'Sneakers & Footwear',
  'Sporting Goods',
  'Supplements & Nutrition',
  'Toys & Games',
  'Wine & Spirits',
  'Other',
]
