[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/s/*"
  to = "/.netlify/functions/og-redirect"
  status = 200

[[redirects]]
  from = "/01/*"
  to = "/.netlify/functions/og-redirect"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
