[build]
  publish = "public"
  functions = "netlify/functions"
  environment = { SECRETS_SCAN_OMIT_PATHS = "public/shared/app.js" }

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/patient/*"
  to = "/patient/:splat"
  status = 200

[[redirects]]
  from = "/doctor/*"
  to = "/doctor/:splat"
  status = 200
